// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module svm_detect (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        cells_bin_V_2,
        cells_bin_V_2_ap_vld,
        cells_bin_V_address0,
        cells_bin_V_ce0,
        cells_bin_V_q0,
        cells_bin_V_address1,
        cells_bin_V_ce1,
        cells_bin_V_q1,
        cells_mag_sq_V_address0,
        cells_mag_sq_V_ce0,
        cells_mag_sq_V_q0,
        cells_mag_sq_V_address1,
        cells_mag_sq_V_ce1,
        cells_mag_sq_V_q1
);

parameter    ap_ST_fsm_state1 = 52'd1;
parameter    ap_ST_fsm_state2 = 52'd2;
parameter    ap_ST_fsm_state3 = 52'd4;
parameter    ap_ST_fsm_state4 = 52'd8;
parameter    ap_ST_fsm_state5 = 52'd16;
parameter    ap_ST_fsm_state6 = 52'd32;
parameter    ap_ST_fsm_state7 = 52'd64;
parameter    ap_ST_fsm_state8 = 52'd128;
parameter    ap_ST_fsm_state9 = 52'd256;
parameter    ap_ST_fsm_state10 = 52'd512;
parameter    ap_ST_fsm_state11 = 52'd1024;
parameter    ap_ST_fsm_state12 = 52'd2048;
parameter    ap_ST_fsm_state13 = 52'd4096;
parameter    ap_ST_fsm_state14 = 52'd8192;
parameter    ap_ST_fsm_state15 = 52'd16384;
parameter    ap_ST_fsm_state16 = 52'd32768;
parameter    ap_ST_fsm_state17 = 52'd65536;
parameter    ap_ST_fsm_state18 = 52'd131072;
parameter    ap_ST_fsm_state19 = 52'd262144;
parameter    ap_ST_fsm_state20 = 52'd524288;
parameter    ap_ST_fsm_state21 = 52'd1048576;
parameter    ap_ST_fsm_state22 = 52'd2097152;
parameter    ap_ST_fsm_state23 = 52'd4194304;
parameter    ap_ST_fsm_state24 = 52'd8388608;
parameter    ap_ST_fsm_state25 = 52'd16777216;
parameter    ap_ST_fsm_state26 = 52'd33554432;
parameter    ap_ST_fsm_state27 = 52'd67108864;
parameter    ap_ST_fsm_state28 = 52'd134217728;
parameter    ap_ST_fsm_state29 = 52'd268435456;
parameter    ap_ST_fsm_state30 = 52'd536870912;
parameter    ap_ST_fsm_state31 = 52'd1073741824;
parameter    ap_ST_fsm_state32 = 52'd2147483648;
parameter    ap_ST_fsm_state33 = 52'd4294967296;
parameter    ap_ST_fsm_state34 = 52'd8589934592;
parameter    ap_ST_fsm_state35 = 52'd17179869184;
parameter    ap_ST_fsm_state36 = 52'd34359738368;
parameter    ap_ST_fsm_state37 = 52'd68719476736;
parameter    ap_ST_fsm_state38 = 52'd137438953472;
parameter    ap_ST_fsm_state39 = 52'd274877906944;
parameter    ap_ST_fsm_state40 = 52'd549755813888;
parameter    ap_ST_fsm_state41 = 52'd1099511627776;
parameter    ap_ST_fsm_state42 = 52'd2199023255552;
parameter    ap_ST_fsm_state43 = 52'd4398046511104;
parameter    ap_ST_fsm_state44 = 52'd8796093022208;
parameter    ap_ST_fsm_state45 = 52'd17592186044416;
parameter    ap_ST_fsm_state46 = 52'd35184372088832;
parameter    ap_ST_fsm_state47 = 52'd70368744177664;
parameter    ap_ST_fsm_state48 = 52'd140737488355328;
parameter    ap_ST_fsm_state49 = 52'd281474976710656;
parameter    ap_ST_fsm_state50 = 52'd562949953421312;
parameter    ap_ST_fsm_state51 = 52'd1125899906842624;
parameter    ap_ST_fsm_state52 = 52'd2251799813685248;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] cells_bin_V_2;
output   cells_bin_V_2_ap_vld;
output  [9:0] cells_bin_V_address0;
output   cells_bin_V_ce0;
input  [31:0] cells_bin_V_q0;
output  [9:0] cells_bin_V_address1;
output   cells_bin_V_ce1;
input  [31:0] cells_bin_V_q1;
output  [5:0] cells_mag_sq_V_address0;
output   cells_mag_sq_V_ce0;
input  [63:0] cells_mag_sq_V_q0;
output  [5:0] cells_mag_sq_V_address1;
output   cells_mag_sq_V_ce1;
input  [63:0] cells_mag_sq_V_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg cells_bin_V_2_ap_vld;
reg[9:0] cells_bin_V_address0;
reg cells_bin_V_ce0;
reg[9:0] cells_bin_V_address1;
reg cells_bin_V_ce1;
reg[5:0] cells_mag_sq_V_address0;
reg cells_mag_sq_V_ce0;
reg[5:0] cells_mag_sq_V_address1;
reg cells_mag_sq_V_ce1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [51:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] SVM_detector_V_address0;
reg    SVM_detector_V_ce0;
wire   [13:0] SVM_detector_V_q0;
reg   [10:0] SVM_detector_V_address1;
reg    SVM_detector_V_ce1;
wire   [13:0] SVM_detector_V_q1;
wire   [31:0] grp_fu_332_p2;
reg   [31:0] reg_342;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state33;
reg   [31:0] reg_349;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
reg   [31:0] reg_353;
reg   [13:0] reg_357;
wire    ap_CS_fsm_state41;
reg   [13:0] reg_361;
wire   [2:0] i_1_fu_385_p2;
reg   [2:0] i_1_reg_1624;
wire    ap_CS_fsm_state2;
wire   [6:0] tmp_5_fu_403_p2;
reg   [6:0] tmp_5_reg_1633;
wire   [0:0] exitcond2_fu_379_p2;
reg   [0:0] is_neg_1_reg_1644;
wire   [31:0] tmp_7_fu_420_p2;
reg   [31:0] tmp_7_reg_1650;
wire   [2:0] j_1_fu_432_p2;
reg   [2:0] j_1_reg_1658;
wire    ap_CS_fsm_state3;
wire   [5:0] tmp_4_fu_438_p3;
reg   [5:0] tmp_4_reg_1667;
wire   [0:0] exitcond3_fu_426_p2;
wire   [5:0] tmp_11_fu_451_p3;
reg   [5:0] tmp_11_reg_1677;
wire    ap_CS_fsm_state4;
reg   [63:0] p_Val2_18_reg_1687;
wire   [5:0] tmp_23_fu_463_p3;
reg   [5:0] tmp_23_reg_1692;
wire   [5:0] tmp_39_fu_475_p3;
reg   [5:0] tmp_39_reg_1702;
wire    ap_CS_fsm_state5;
wire   [63:0] tmp1_fu_486_p2;
reg   [63:0] tmp1_reg_1712;
wire   [63:0] p_Val2_23_fu_497_p2;
reg   [63:0] p_Val2_23_reg_1717;
wire    ap_CS_fsm_state6;
reg   [0:0] is_neg_reg_1724;
wire   [63:0] tmp_13_fu_510_p2;
reg   [63:0] tmp_13_reg_1730;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_12_fu_515_p2;
reg   [0:0] tmp_12_reg_1735;
wire    ap_CS_fsm_state8;
wire   [63:0] p_Val2_31_fu_520_p3;
reg   [63:0] p_Val2_31_reg_1741;
wire   [31:0] num_zeros_1_fu_543_p1;
reg   [31:0] num_zeros_1_reg_1747;
wire   [7:0] tmp_50_fu_547_p1;
reg   [7:0] tmp_50_reg_1752;
wire   [31:0] tmp32_V_7_fu_610_p3;
reg   [31:0] tmp32_V_7_reg_1757;
wire    ap_CS_fsm_state9;
wire   [31:0] tmp32_V_12_fu_618_p1;
reg   [31:0] tmp32_V_12_reg_1762;
wire    ap_CS_fsm_state15;
wire   [0:0] tmp_19_fu_632_p2;
reg   [0:0] tmp_19_reg_1767;
wire   [31:0] yn_fu_694_p3;
reg   [31:0] yn_reg_1772;
wire    ap_CS_fsm_state16;
wire   [31:0] x_fu_705_p3;
reg   [31:0] x_reg_1778;
wire   [31:0] grp_fu_327_p2;
reg   [31:0] tmp_24_reg_1783;
wire    ap_CS_fsm_state29;
reg   [0:0] isneg_reg_1788;
wire    ap_CS_fsm_state34;
reg   [10:0] exp_tmp_V_reg_1794;
wire   [51:0] tmp_95_fu_738_p1;
reg   [51:0] tmp_95_reg_1799;
wire   [0:0] tmp_27_fu_742_p2;
reg   [0:0] tmp_27_reg_1804;
wire   [53:0] p_Result_2_fu_758_p1;
reg   [53:0] p_Result_2_reg_1810;
wire    ap_CS_fsm_state35;
wire   [53:0] man_V_1_fu_762_p2;
reg   [53:0] man_V_1_reg_1815;
wire   [0:0] tmp_28_fu_774_p2;
reg   [0:0] tmp_28_reg_1820;
wire  signed [11:0] sh_amt_fu_792_p3;
reg  signed [11:0] sh_amt_reg_1826;
wire   [0:0] tmp_31_fu_800_p2;
reg   [0:0] tmp_31_reg_1832;
wire   [0:0] icmp1_fu_816_p2;
reg   [0:0] icmp1_reg_1838;
wire   [53:0] man_V_2_fu_822_p3;
reg   [53:0] man_V_2_reg_1843;
wire    ap_CS_fsm_state36;
wire  signed [31:0] sh_amt_cast_fu_827_p1;
reg  signed [31:0] sh_amt_cast_reg_1848;
wire   [0:0] sel_tmp5_fu_899_p2;
reg   [0:0] sel_tmp5_reg_1853;
wire   [0:0] or_cond_fu_904_p2;
reg   [0:0] or_cond_reg_1858;
wire   [0:0] or_cond2_fu_916_p2;
reg   [0:0] or_cond2_reg_1863;
wire   [30:0] tmp_78_fu_942_p3;
reg   [30:0] tmp_78_reg_1868;
wire   [9:0] tmp_10_fu_967_p2;
reg   [9:0] tmp_10_reg_1873;
wire    ap_CS_fsm_state37;
wire   [9:0] tmp_18_fu_989_p2;
reg   [9:0] tmp_18_reg_1878;
wire   [9:0] tmp_37_fu_1011_p2;
reg   [9:0] tmp_37_reg_1883;
wire   [9:0] tmp_45_fu_1032_p2;
reg   [9:0] tmp_45_reg_1888;
wire   [11:0] tmp_42_fu_1092_p3;
reg   [11:0] tmp_42_reg_1893;
wire  signed [9:0] tmp_77_cast_cast_fu_1108_p1;
reg  signed [9:0] tmp_77_cast_cast_reg_1898;
wire  signed [62:0] OP2_V_cast_fu_1112_p1;
reg  signed [62:0] OP2_V_cast_reg_1903;
wire   [3:0] k_1_fu_1122_p2;
reg   [3:0] k_1_reg_1914;
wire    ap_CS_fsm_state38;
wire   [11:0] SVM_index_fu_1141_p2;
reg   [11:0] SVM_index_reg_1919;
wire   [0:0] exitcond_fu_1116_p2;
wire   [9:0] tmp_83_fu_1166_p2;
reg   [9:0] tmp_83_reg_1934;
wire   [9:0] tmp_84_fu_1171_p2;
reg   [9:0] tmp_84_reg_1939;
wire   [16:0] tmp_72_cast_fu_1192_p1;
reg   [16:0] tmp_72_cast_reg_1959;
reg   [31:0] tmp_47_reg_1970;
reg   [31:0] tmp_49_reg_1975;
reg   [31:0] tmp_51_reg_1990;
reg   [31:0] tmp_53_reg_1995;
wire   [44:0] p_Val2_6_fu_1310_p2;
reg   [44:0] p_Val2_6_reg_2000;
wire   [44:0] p_Val2_9_fu_1323_p2;
reg   [44:0] p_Val2_9_reg_2005;
wire   [44:0] p_Val2_8_fu_1399_p2;
reg   [44:0] p_Val2_8_reg_2010;
wire    ap_CS_fsm_state42;
reg   [31:0] tmp_86_reg_2015;
wire   [44:0] p_Val2_4_fu_1422_p2;
reg   [44:0] p_Val2_4_reg_2020;
reg   [31:0] result_V_reg_2025;
wire    ap_CS_fsm_state43;
wire   [0:0] tmp_s_fu_1505_p2;
reg   [0:0] tmp_s_reg_2031;
wire    ap_CS_fsm_state45;
wire   [31:0] tmp32_V_1_fu_1533_p2;
reg   [31:0] tmp32_V_1_reg_2036;
wire   [7:0] tmp_fu_1539_p1;
reg   [7:0] tmp_reg_2041;
wire   [31:0] tmp32_V_fu_1543_p1;
reg   [31:0] tmp32_V_reg_2046;
wire    ap_CS_fsm_state51;
wire   [0:0] tmp_1_fu_1557_p2;
reg   [0:0] tmp_1_reg_2051;
reg   [2:0] i_reg_292;
reg    ap_block_state1;
reg   [2:0] j_reg_304;
reg   [3:0] k_reg_316;
wire    ap_CS_fsm_state44;
wire   [63:0] tmp_8_fu_446_p1;
wire   [63:0] tmp_15_fu_458_p1;
wire   [63:0] tmp_32_fu_470_p1;
wire   [63:0] tmp_40_fu_481_p1;
wire   [63:0] tmp_84_cast_fu_1151_p1;
wire   [63:0] tmp_85_cast_fu_1161_p1;
wire   [63:0] tmp_86_cast_fu_1179_p1;
wire   [63:0] tmp_87_cast_fu_1183_p1;
wire   [63:0] tmp_54_fu_1187_p1;
wire   [63:0] tmp_59_fu_1202_p1;
wire   [63:0] tmp_64_fu_1250_p1;
wire   [63:0] tmp_69_fu_1260_p1;
reg   [31:0] p_Val2_s_fu_160;
reg   [31:0] p_Val2_7_fu_164;
wire    ap_CS_fsm_state52;
wire    ap_CS_fsm_state25;
reg   [31:0] grp_fu_332_p0;
reg   [31:0] grp_fu_332_p1;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state30;
reg   [31:0] grp_fu_336_p0;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state46;
wire   [5:0] p_shl_fu_391_p3;
wire   [6:0] p_shl_cast_fu_399_p1;
wire   [6:0] i_cast_fu_375_p1;
wire   [63:0] tmp2_fu_492_p2;
reg   [63:0] p_Result_s_fu_525_p4;
reg   [63:0] tmp_14_fu_535_p3;
wire   [31:0] msb_idx_fu_551_p2;
wire   [26:0] tmp_52_fu_556_p4;
wire   [31:0] tmp32_V_5_fu_572_p1;
wire   [31:0] tmp_17_fu_575_p2;
wire   [5:0] tmp_62_fu_587_p1;
wire   [5:0] tmp_67_fu_591_p2;
wire   [63:0] tmp_72_fu_597_p1;
wire   [63:0] tmp_91_fu_601_p2;
wire   [0:0] icmp_fu_566_p2;
wire   [31:0] tmp32_V_3_fu_581_p2;
wire   [31:0] tmp32_V_6_fu_606_p1;
wire   [31:0] grp_fu_336_p1;
wire   [7:0] p_Result_s_24_fu_622_p4;
wire   [7:0] tmp_21_fu_643_p1;
wire   [7:0] tmp_20_fu_638_p2;
wire   [7:0] p_Repl2_4_trunc_fu_646_p2;
wire   [8:0] tmp_22_fu_652_p3;
wire   [31:0] p_Result_1_fu_659_p5;
wire   [30:0] tmp_46_fu_670_p4;
wire   [31:0] tmp_48_fu_680_p1;
wire   [31:0] p_op_fu_684_p2;
wire   [31:0] tmp_57_fu_690_p1;
wire   [31:0] f_3_fu_701_p1;
wire   [63:0] d_assign_fu_339_p1;
wire   [63:0] ireg_V_fu_712_p1;
wire   [62:0] tmp_93_fu_716_p1;
wire   [52:0] tmp_26_fu_751_p3;
wire   [11:0] tmp_25_fu_748_p1;
wire   [11:0] F2_fu_768_p2;
wire   [11:0] tmp_29_fu_780_p2;
wire   [11:0] tmp_30_fu_786_p2;
wire   [6:0] tmp_97_fu_806_p4;
wire   [53:0] tmp_35_fu_835_p1;
wire   [0:0] sel_tmp1_fu_845_p2;
wire   [0:0] sel_tmp6_demorgan_fu_855_p2;
wire   [0:0] sel_tmp6_fu_859_p2;
wire   [0:0] sel_tmp7_fu_865_p2;
wire   [0:0] tmp_33_fu_830_p2;
wire   [0:0] sel_tmp_fu_876_p2;
wire   [0:0] sel_tmp21_demorgan_fu_888_p2;
wire   [0:0] sel_tmp4_fu_893_p2;
wire   [0:0] sel_tmp3_fu_882_p2;
wire   [0:0] sel_tmp8_fu_870_p2;
wire   [0:0] sel_tmp2_fu_850_p2;
wire   [0:0] or_cond1_fu_910_p2;
wire   [53:0] tmp_36_fu_839_p2;
wire   [30:0] tmp_76_fu_922_p4;
wire   [30:0] tmp_77_fu_932_p4;
wire   [8:0] tmp_6_fu_953_p4;
wire   [9:0] p_shl4_cast_fu_963_p1;
wire   [9:0] tmp_8_cast_fu_950_p1;
wire   [8:0] tmp_16_fu_976_p4;
wire   [9:0] p_shl3_cast_fu_985_p1;
wire   [9:0] tmp_37_cast_fu_973_p1;
wire   [8:0] tmp_34_fu_998_p4;
wire   [9:0] p_shl2_cast_fu_1007_p1;
wire   [9:0] tmp_48_cast_fu_995_p1;
wire   [8:0] tmp_44_fu_1020_p4;
wire   [9:0] p_shl1_cast_fu_1028_p1;
wire   [9:0] tmp_62_cast_fu_1017_p1;
wire   [31:0] tmp_96_fu_1038_p1;
wire   [31:0] tmp_38_fu_1041_p2;
wire   [30:0] tmp_73_fu_1046_p4;
wire   [30:0] tmp_74_fu_1056_p3;
wire   [30:0] tmp_75_fu_1063_p3;
wire   [30:0] tmp_79_fu_1070_p3;
wire   [6:0] tmp_55_cast_fu_1083_p1;
wire   [6:0] tmp_41_fu_1087_p2;
wire   [8:0] tmp_43_fu_1100_p3;
wire   [30:0] tmp_80_fu_1076_p3;
wire   [9:0] tmp_89_cast_cast_fu_1128_p1;
wire   [9:0] tmp3_fu_1132_p2;
wire  signed [11:0] tmp29_cast_fu_1137_p1;
wire   [9:0] tmp_81_fu_1146_p2;
wire   [9:0] tmp_82_fu_1156_p2;
wire  signed [15:0] SVM_index_cast_fu_1176_p1;
wire   [16:0] tmp_58_fu_1196_p2;
wire  signed [31:0] p_Val2_1_fu_1211_p0;
wire  signed [30:0] p_Val2_1_fu_1211_p1;
wire   [62:0] p_Val2_1_fu_1211_p2;
wire  signed [31:0] p_Val2_2_fu_1230_p0;
wire  signed [30:0] p_Val2_2_fu_1230_p1;
wire   [62:0] p_Val2_2_fu_1230_p2;
wire   [16:0] tmp_63_fu_1245_p2;
wire   [16:0] tmp_68_fu_1255_p2;
wire  signed [31:0] p_Val2_3_fu_1269_p0;
wire  signed [30:0] p_Val2_3_fu_1269_p1;
wire   [62:0] p_Val2_3_fu_1269_p2;
wire  signed [31:0] p_Val2_5_fu_1288_p0;
wire  signed [30:0] p_Val2_5_fu_1288_p1;
wire   [62:0] p_Val2_5_fu_1288_p2;
wire  signed [31:0] p_Val2_6_fu_1310_p0;
wire  signed [13:0] p_Val2_6_fu_1310_p1;
wire  signed [31:0] p_Val2_9_fu_1323_p0;
wire  signed [13:0] p_Val2_9_fu_1323_p1;
wire   [47:0] tmp_55_fu_1335_p3;
wire  signed [63:0] p_Val2_6_cast_fu_1332_p1;
wire   [64:0] tmp_56_fu_1347_p1;
wire   [64:0] tmp_69_cast_fu_1343_p1;
wire   [64:0] p_Val2_34_fu_1351_p2;
wire   [31:0] tmp_85_fu_1360_p4;
wire   [47:0] tmp_60_fu_1370_p3;
wire  signed [63:0] p_Val2_9_cast_fu_1357_p1;
wire   [64:0] tmp_61_fu_1382_p1;
wire   [64:0] tmp_76_cast_fu_1378_p1;
wire  signed [31:0] p_Val2_8_fu_1399_p0;
wire  signed [13:0] p_Val2_8_fu_1399_p1;
wire   [64:0] p_Val2_35_fu_1386_p2;
wire  signed [31:0] p_Val2_4_fu_1422_p0;
wire  signed [13:0] p_Val2_4_fu_1422_p1;
wire   [47:0] tmp_65_fu_1431_p3;
wire  signed [63:0] p_Val2_10_cast_fu_1428_p1;
wire   [64:0] tmp_66_fu_1442_p1;
wire   [64:0] tmp_82_cast_fu_1438_p1;
wire   [64:0] p_Val2_36_fu_1446_p2;
wire   [31:0] tmp_87_fu_1455_p4;
wire   [47:0] tmp_70_fu_1465_p3;
wire  signed [63:0] p_Val2_11_cast_fu_1452_p1;
wire   [64:0] tmp_71_fu_1477_p1;
wire   [64:0] tmp_88_cast_fu_1473_p1;
wire   [64:0] p_Val2_37_fu_1481_p2;
wire   [31:0] p_Val2_38_fu_1510_p3;
reg   [31:0] p_Result_4_fu_1515_p4;
reg   [31:0] num_zeros_fu_1525_p3;
wire   [7:0] p_Result_3_fu_1547_p4;
wire   [7:0] tmp_2_fu_1563_p2;
wire   [7:0] tmp_9_fu_1568_p1;
wire   [7:0] p_Repl2_1_trunc_fu_1571_p2;
wire   [8:0] tmp_3_fu_1577_p3;
wire   [31:0] p_Result_5_fu_1584_p5;
wire   [31:0] f_fu_1595_p1;
reg   [51:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 52'd1;
end

svm_detect_SVM_decud #(
    .DataWidth( 14 ),
    .AddressRange( 1764 ),
    .AddressWidth( 11 ))
SVM_detector_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(SVM_detector_V_address0),
    .ce0(SVM_detector_V_ce0),
    .q0(SVM_detector_V_q0),
    .address1(SVM_detector_V_address1),
    .ce1(SVM_detector_V_ce1),
    .q1(SVM_detector_V_q1)
);

xillybus_wrapper_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
xillybus_wrapper_dEe_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1077936128),
    .din1(reg_342),
    .ce(1'b1),
    .dout(grp_fu_327_p2)
);

xillybus_wrapper_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
xillybus_wrapper_eOg_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_332_p0),
    .din1(grp_fu_332_p1),
    .ce(1'b1),
    .dout(grp_fu_332_p2)
);

xillybus_wrapper_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
xillybus_wrapper_fYi_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_336_p0),
    .ce(1'b1),
    .dout(grp_fu_336_p1)
);

xillybus_wrapper_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
xillybus_wrapper_g8j_U14(
    .din0(reg_342),
    .dout(d_assign_fu_339_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state52)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond3_fu_426_p2 == 1'd1))) begin
        i_reg_292 <= i_1_reg_1624;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_292 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state38) & (exitcond_fu_1116_p2 == 1'd1))) begin
        j_reg_304 <= j_1_reg_1658;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_379_p2 == 1'd0))) begin
        j_reg_304 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        k_reg_316 <= k_1_reg_1914;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        k_reg_316 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        p_Val2_7_fu_164 <= result_V_reg_2025;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_7_fu_164 <= 32'd4294947474;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        p_Val2_s_fu_160 <= result_V_reg_2025;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_s_fu_160 <= 32'd4294947474;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        OP2_V_cast_reg_1903 <= OP2_V_cast_fu_1112_p1;
        tmp_10_reg_1873 <= tmp_10_fu_967_p2;
        tmp_18_reg_1878 <= tmp_18_fu_989_p2;
        tmp_37_reg_1883 <= tmp_37_fu_1011_p2;
        tmp_42_reg_1893[11 : 5] <= tmp_42_fu_1092_p3[11 : 5];
        tmp_45_reg_1888 <= tmp_45_fu_1032_p2;
        tmp_77_cast_cast_reg_1898[9 : 2] <= tmp_77_cast_cast_fu_1108_p1[9 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state38) & (exitcond_fu_1116_p2 == 1'd0))) begin
        SVM_index_reg_1919 <= SVM_index_fu_1141_p2;
        tmp_83_reg_1934 <= tmp_83_fu_1166_p2;
        tmp_84_reg_1939 <= tmp_84_fu_1171_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        exp_tmp_V_reg_1794 <= {{ireg_V_fu_712_p1[62:52]}};
        isneg_reg_1788 <= ireg_V_fu_712_p1[32'd63];
        tmp_27_reg_1804 <= tmp_27_fu_742_p2;
        tmp_95_reg_1799 <= tmp_95_fu_738_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_1624 <= i_1_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        icmp1_reg_1838 <= icmp1_fu_816_p2;
        p_Result_2_reg_1810[51 : 0] <= p_Result_2_fu_758_p1[51 : 0];
        sh_amt_reg_1826 <= sh_amt_fu_792_p3;
        tmp_28_reg_1820 <= tmp_28_fu_774_p2;
        tmp_31_reg_1832 <= tmp_31_fu_800_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_379_p2 == 1'd1))) begin
        is_neg_1_reg_1644 <= p_Val2_s_fu_160[32'd31];
        tmp_7_reg_1650 <= tmp_7_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        is_neg_reg_1724 <= p_Val2_23_fu_497_p2[32'd63];
        p_Val2_23_reg_1717 <= p_Val2_23_fu_497_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_1_reg_1658 <= j_1_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        k_1_reg_1914 <= k_1_fu_1122_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) & (isneg_reg_1788 == 1'd1))) begin
        man_V_1_reg_1815 <= man_V_1_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        man_V_2_reg_1843 <= man_V_2_fu_822_p3;
        or_cond2_reg_1863 <= or_cond2_fu_916_p2;
        or_cond_reg_1858 <= or_cond_fu_904_p2;
        sel_tmp5_reg_1853 <= sel_tmp5_fu_899_p2;
        sh_amt_cast_reg_1848 <= sh_amt_cast_fu_827_p1;
        tmp_78_reg_1868 <= tmp_78_fu_942_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        num_zeros_1_reg_1747 <= num_zeros_1_fu_543_p1;
        p_Val2_31_reg_1741 <= p_Val2_31_fu_520_p3;
        tmp_12_reg_1735 <= tmp_12_fu_515_p2;
        tmp_50_reg_1752 <= tmp_50_fu_547_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_18_reg_1687 <= cells_mag_sq_V_q0;
        tmp_11_reg_1677 <= tmp_11_fu_451_p3;
        tmp_23_reg_1692 <= tmp_23_fu_463_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        p_Val2_4_reg_2020 <= p_Val2_4_fu_1422_p2;
        p_Val2_8_reg_2010 <= p_Val2_8_fu_1399_p2;
        tmp_86_reg_2015 <= {{p_Val2_35_fu_1386_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        p_Val2_6_reg_2000 <= p_Val2_6_fu_1310_p2;
        p_Val2_9_reg_2005 <= p_Val2_9_fu_1323_p2;
        tmp_51_reg_1990 <= {{p_Val2_3_fu_1269_p2[47:16]}};
        tmp_53_reg_1995 <= {{p_Val2_5_fu_1288_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state20))) begin
        reg_342 <= grp_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39))) begin
        reg_349 <= cells_bin_V_q0;
        reg_353 <= cells_bin_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40))) begin
        reg_357 <= SVM_detector_V_q0;
        reg_361 <= SVM_detector_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_V_reg_2025 <= {{p_Val2_37_fu_1481_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp1_reg_1712 <= tmp1_fu_486_p2;
        tmp_39_reg_1702 <= tmp_39_fu_475_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp32_V_12_reg_1762 <= tmp32_V_12_fu_618_p1;
        tmp_19_reg_1767 <= tmp_19_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        tmp32_V_1_reg_2036 <= tmp32_V_1_fu_1533_p2;
        tmp_reg_2041 <= tmp_fu_1539_p1;
        tmp_s_reg_2031 <= tmp_s_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp32_V_7_reg_1757 <= tmp32_V_7_fu_610_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state51) & (tmp_s_reg_2031 == 1'd0))) begin
        tmp32_V_reg_2046 <= tmp32_V_fu_1543_p1;
        tmp_1_reg_2051 <= tmp_1_fu_1557_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (is_neg_reg_1724 == 1'd1))) begin
        tmp_13_reg_1730 <= tmp_13_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        tmp_24_reg_1783 <= grp_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        tmp_47_reg_1970 <= {{p_Val2_1_fu_1211_p2[47:16]}};
        tmp_49_reg_1975 <= {{p_Val2_2_fu_1230_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond3_fu_426_p2 == 1'd0))) begin
        tmp_4_reg_1667 <= tmp_4_fu_438_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_379_p2 == 1'd0))) begin
        tmp_5_reg_1633 <= tmp_5_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        tmp_72_cast_reg_1959[15 : 0] <= tmp_72_cast_fu_1192_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_reg_1778 <= x_fu_705_p3;
        yn_reg_1772 <= yn_fu_694_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        SVM_detector_V_address0 = tmp_64_fu_1250_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        SVM_detector_V_address0 = tmp_54_fu_1187_p1;
    end else begin
        SVM_detector_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        SVM_detector_V_address1 = tmp_69_fu_1260_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        SVM_detector_V_address1 = tmp_59_fu_1202_p1;
    end else begin
        SVM_detector_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39))) begin
        SVM_detector_V_ce0 = 1'b1;
    end else begin
        SVM_detector_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39))) begin
        SVM_detector_V_ce1 = 1'b1;
    end else begin
        SVM_detector_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        cells_bin_V_2_ap_vld = 1'b1;
    end else begin
        cells_bin_V_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        cells_bin_V_address0 = tmp_86_cast_fu_1179_p1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        cells_bin_V_address0 = tmp_84_cast_fu_1151_p1;
    end else begin
        cells_bin_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        cells_bin_V_address1 = tmp_87_cast_fu_1183_p1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        cells_bin_V_address1 = tmp_85_cast_fu_1161_p1;
    end else begin
        cells_bin_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state39))) begin
        cells_bin_V_ce0 = 1'b1;
    end else begin
        cells_bin_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state39))) begin
        cells_bin_V_ce1 = 1'b1;
    end else begin
        cells_bin_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cells_mag_sq_V_address0 = tmp_15_fu_458_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        cells_mag_sq_V_address0 = tmp_8_fu_446_p1;
    end else begin
        cells_mag_sq_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cells_mag_sq_V_address1 = tmp_40_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        cells_mag_sq_V_address1 = tmp_32_fu_470_p1;
    end else begin
        cells_mag_sq_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        cells_mag_sq_V_ce0 = 1'b1;
    end else begin
        cells_mag_sq_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        cells_mag_sq_V_ce1 = 1'b1;
    end else begin
        cells_mag_sq_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_332_p0 = reg_342;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_332_p0 = yn_reg_1772;
    end else begin
        grp_fu_332_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_332_p1 = tmp_24_reg_1783;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_332_p1 = x_reg_1778;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_332_p1 = yn_reg_1772;
    end else begin
        grp_fu_332_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_336_p0 = tmp32_V_1_reg_2036;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_336_p0 = tmp32_V_7_reg_1757;
    end else begin
        grp_fu_336_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_379_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond3_fu_426_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((1'b1 == ap_CS_fsm_state38) & (exitcond_fu_1116_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_768_p2 = (12'd1075 - tmp_25_fu_748_p1);

assign OP2_V_cast_fu_1112_p1 = $signed(tmp_80_fu_1076_p3);

assign SVM_index_cast_fu_1176_p1 = $signed(SVM_index_reg_1919);

assign SVM_index_fu_1141_p2 = ($signed(tmp29_cast_fu_1137_p1) + $signed(tmp_42_reg_1893));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cells_bin_V_2 = ((tmp_s_reg_2031[0:0] === 1'b1) ? 32'd0 : f_fu_1595_p1);

assign exitcond2_fu_379_p2 = ((i_reg_292 == 3'd7) ? 1'b1 : 1'b0);

assign exitcond3_fu_426_p2 = ((j_reg_304 == 3'd7) ? 1'b1 : 1'b0);

assign exitcond_fu_1116_p2 = ((k_reg_316 == 4'd9) ? 1'b1 : 1'b0);

assign f_3_fu_701_p1 = p_Result_1_fu_659_p5;

assign f_fu_1595_p1 = p_Result_5_fu_1584_p5;

assign i_1_fu_385_p2 = (i_reg_292 + 3'd1);

assign i_cast_fu_375_p1 = i_reg_292;

assign icmp1_fu_816_p2 = ((tmp_97_fu_806_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_566_p2 = ((tmp_52_fu_556_p4 == 27'd0) ? 1'b1 : 1'b0);

assign ireg_V_fu_712_p1 = d_assign_fu_339_p1;

assign j_1_fu_432_p2 = (j_reg_304 + 3'd1);

assign k_1_fu_1122_p2 = (k_reg_316 + 4'd1);

assign man_V_1_fu_762_p2 = (54'd0 - p_Result_2_fu_758_p1);

assign man_V_2_fu_822_p3 = ((isneg_reg_1788[0:0] === 1'b1) ? man_V_1_reg_1815 : p_Result_2_reg_1810);

assign msb_idx_fu_551_p2 = (num_zeros_1_reg_1747 ^ 32'd63);

assign num_zeros_1_fu_543_p1 = tmp_14_fu_535_p3[31:0];


always @ (p_Result_4_fu_1515_p4) begin
    if (p_Result_4_fu_1515_p4[0] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd0;
    end else if (p_Result_4_fu_1515_p4[1] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd1;
    end else if (p_Result_4_fu_1515_p4[2] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd2;
    end else if (p_Result_4_fu_1515_p4[3] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd3;
    end else if (p_Result_4_fu_1515_p4[4] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd4;
    end else if (p_Result_4_fu_1515_p4[5] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd5;
    end else if (p_Result_4_fu_1515_p4[6] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd6;
    end else if (p_Result_4_fu_1515_p4[7] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd7;
    end else if (p_Result_4_fu_1515_p4[8] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd8;
    end else if (p_Result_4_fu_1515_p4[9] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd9;
    end else if (p_Result_4_fu_1515_p4[10] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd10;
    end else if (p_Result_4_fu_1515_p4[11] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd11;
    end else if (p_Result_4_fu_1515_p4[12] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd12;
    end else if (p_Result_4_fu_1515_p4[13] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd13;
    end else if (p_Result_4_fu_1515_p4[14] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd14;
    end else if (p_Result_4_fu_1515_p4[15] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd15;
    end else if (p_Result_4_fu_1515_p4[16] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd16;
    end else if (p_Result_4_fu_1515_p4[17] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd17;
    end else if (p_Result_4_fu_1515_p4[18] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd18;
    end else if (p_Result_4_fu_1515_p4[19] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd19;
    end else if (p_Result_4_fu_1515_p4[20] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd20;
    end else if (p_Result_4_fu_1515_p4[21] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd21;
    end else if (p_Result_4_fu_1515_p4[22] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd22;
    end else if (p_Result_4_fu_1515_p4[23] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd23;
    end else if (p_Result_4_fu_1515_p4[24] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd24;
    end else if (p_Result_4_fu_1515_p4[25] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd25;
    end else if (p_Result_4_fu_1515_p4[26] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd26;
    end else if (p_Result_4_fu_1515_p4[27] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd27;
    end else if (p_Result_4_fu_1515_p4[28] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd28;
    end else if (p_Result_4_fu_1515_p4[29] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd29;
    end else if (p_Result_4_fu_1515_p4[30] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd30;
    end else if (p_Result_4_fu_1515_p4[31] == 1'b1) begin
        num_zeros_fu_1525_p3 = 32'd31;
    end else begin
        num_zeros_fu_1525_p3 = 32'd32;
    end
end

assign or_cond1_fu_910_p2 = (sel_tmp8_fu_870_p2 | sel_tmp2_fu_850_p2);

assign or_cond2_fu_916_p2 = (or_cond_fu_904_p2 | or_cond1_fu_910_p2);

assign or_cond_fu_904_p2 = (sel_tmp5_fu_899_p2 | sel_tmp3_fu_882_p2);

assign p_Repl2_1_trunc_fu_1571_p2 = (tmp_2_fu_1563_p2 + tmp_9_fu_1568_p1);

assign p_Repl2_4_trunc_fu_646_p2 = (tmp_21_fu_643_p1 + tmp_20_fu_638_p2);

assign p_Result_1_fu_659_p5 = {{tmp_22_fu_652_p3}, {tmp32_V_12_reg_1762[22:0]}};

assign p_Result_2_fu_758_p1 = tmp_26_fu_751_p3;

assign p_Result_3_fu_1547_p4 = {{tmp32_V_fu_1543_p1[30:23]}};

integer ap_tvar_int_0;

always @ (p_Val2_38_fu_1510_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_4_fu_1515_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_4_fu_1515_p4[ap_tvar_int_0] = p_Val2_38_fu_1510_p3[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_5_fu_1584_p5 = {{tmp_3_fu_1577_p3}, {tmp32_V_reg_2046[22:0]}};

assign p_Result_s_24_fu_622_p4 = {{tmp32_V_12_fu_618_p1[30:23]}};

integer ap_tvar_int_1;

always @ (p_Val2_31_fu_520_p3) begin
    for (ap_tvar_int_1 = 64 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 63 - 0) begin
            p_Result_s_fu_525_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_525_p4[ap_tvar_int_1] = p_Val2_31_fu_520_p3[63 - ap_tvar_int_1];
        end
    end
end

assign p_Val2_10_cast_fu_1428_p1 = $signed(p_Val2_8_reg_2010);

assign p_Val2_11_cast_fu_1452_p1 = $signed(p_Val2_4_reg_2020);

assign p_Val2_1_fu_1211_p0 = reg_349;

assign p_Val2_1_fu_1211_p1 = OP2_V_cast_reg_1903;

assign p_Val2_1_fu_1211_p2 = ($signed(p_Val2_1_fu_1211_p0) * $signed(p_Val2_1_fu_1211_p1));

assign p_Val2_23_fu_497_p2 = (tmp1_reg_1712 + tmp2_fu_492_p2);

assign p_Val2_2_fu_1230_p0 = reg_353;

assign p_Val2_2_fu_1230_p1 = OP2_V_cast_reg_1903;

assign p_Val2_2_fu_1230_p2 = ($signed(p_Val2_2_fu_1230_p0) * $signed(p_Val2_2_fu_1230_p1));

assign p_Val2_31_fu_520_p3 = ((is_neg_reg_1724[0:0] === 1'b1) ? tmp_13_reg_1730 : p_Val2_23_reg_1717);

assign p_Val2_34_fu_1351_p2 = (tmp_56_fu_1347_p1 + tmp_69_cast_fu_1343_p1);

assign p_Val2_35_fu_1386_p2 = (tmp_61_fu_1382_p1 + tmp_76_cast_fu_1378_p1);

assign p_Val2_36_fu_1446_p2 = (tmp_66_fu_1442_p1 + tmp_82_cast_fu_1438_p1);

assign p_Val2_37_fu_1481_p2 = (tmp_71_fu_1477_p1 + tmp_88_cast_fu_1473_p1);

assign p_Val2_38_fu_1510_p3 = ((is_neg_1_reg_1644[0:0] === 1'b1) ? tmp_7_reg_1650 : p_Val2_s_fu_160);

assign p_Val2_3_fu_1269_p0 = reg_349;

assign p_Val2_3_fu_1269_p1 = OP2_V_cast_reg_1903;

assign p_Val2_3_fu_1269_p2 = ($signed(p_Val2_3_fu_1269_p0) * $signed(p_Val2_3_fu_1269_p1));

assign p_Val2_4_fu_1422_p0 = tmp_53_reg_1995;

assign p_Val2_4_fu_1422_p1 = reg_361;

assign p_Val2_4_fu_1422_p2 = ($signed(p_Val2_4_fu_1422_p0) * $signed(p_Val2_4_fu_1422_p1));

assign p_Val2_5_fu_1288_p0 = reg_353;

assign p_Val2_5_fu_1288_p1 = OP2_V_cast_reg_1903;

assign p_Val2_5_fu_1288_p2 = ($signed(p_Val2_5_fu_1288_p0) * $signed(p_Val2_5_fu_1288_p1));

assign p_Val2_6_cast_fu_1332_p1 = $signed(p_Val2_6_reg_2000);

assign p_Val2_6_fu_1310_p0 = tmp_47_reg_1970;

assign p_Val2_6_fu_1310_p1 = reg_357;

assign p_Val2_6_fu_1310_p2 = ($signed(p_Val2_6_fu_1310_p0) * $signed(p_Val2_6_fu_1310_p1));

assign p_Val2_8_fu_1399_p0 = tmp_51_reg_1990;

assign p_Val2_8_fu_1399_p1 = reg_357;

assign p_Val2_8_fu_1399_p2 = ($signed(p_Val2_8_fu_1399_p0) * $signed(p_Val2_8_fu_1399_p1));

assign p_Val2_9_cast_fu_1357_p1 = $signed(p_Val2_9_reg_2005);

assign p_Val2_9_fu_1323_p0 = tmp_49_reg_1975;

assign p_Val2_9_fu_1323_p1 = reg_361;

assign p_Val2_9_fu_1323_p2 = ($signed(p_Val2_9_fu_1323_p0) * $signed(p_Val2_9_fu_1323_p1));

assign p_op_fu_684_p2 = (32'd1597463007 - tmp_48_fu_680_p1);

assign p_shl1_cast_fu_1028_p1 = tmp_44_fu_1020_p4;

assign p_shl2_cast_fu_1007_p1 = tmp_34_fu_998_p4;

assign p_shl3_cast_fu_985_p1 = tmp_16_fu_976_p4;

assign p_shl4_cast_fu_963_p1 = tmp_6_fu_953_p4;

assign p_shl_cast_fu_399_p1 = p_shl_fu_391_p3;

assign p_shl_fu_391_p3 = {{i_reg_292}, {3'd0}};

assign sel_tmp1_fu_845_p2 = (tmp_27_reg_1804 ^ 1'd1);

assign sel_tmp21_demorgan_fu_888_p2 = (tmp_28_reg_1820 | sel_tmp6_demorgan_fu_855_p2);

assign sel_tmp2_fu_850_p2 = (tmp_31_reg_1832 & sel_tmp1_fu_845_p2);

assign sel_tmp3_fu_882_p2 = (sel_tmp_fu_876_p2 & sel_tmp7_fu_865_p2);

assign sel_tmp4_fu_893_p2 = (sel_tmp21_demorgan_fu_888_p2 ^ 1'd1);

assign sel_tmp5_fu_899_p2 = (sel_tmp4_fu_893_p2 & icmp1_reg_1838);

assign sel_tmp6_demorgan_fu_855_p2 = (tmp_31_reg_1832 | tmp_27_reg_1804);

assign sel_tmp6_fu_859_p2 = (sel_tmp6_demorgan_fu_855_p2 ^ 1'd1);

assign sel_tmp7_fu_865_p2 = (tmp_28_reg_1820 & sel_tmp6_fu_859_p2);

assign sel_tmp8_fu_870_p2 = (tmp_33_fu_830_p2 & sel_tmp7_fu_865_p2);

assign sel_tmp_fu_876_p2 = (tmp_33_fu_830_p2 ^ 1'd1);

assign sh_amt_cast_fu_827_p1 = sh_amt_reg_1826;

assign sh_amt_fu_792_p3 = ((tmp_28_fu_774_p2[0:0] === 1'b1) ? tmp_29_fu_780_p2 : tmp_30_fu_786_p2);

assign tmp1_fu_486_p2 = (cells_mag_sq_V_q1 + cells_mag_sq_V_q0);

assign tmp29_cast_fu_1137_p1 = $signed(tmp3_fu_1132_p2);

assign tmp2_fu_492_p2 = (cells_mag_sq_V_q1 + p_Val2_18_reg_1687);

assign tmp32_V_12_fu_618_p1 = grp_fu_336_p1;

assign tmp32_V_1_fu_1533_p2 = p_Val2_38_fu_1510_p3 << num_zeros_fu_1525_p3;

assign tmp32_V_3_fu_581_p2 = tmp32_V_5_fu_572_p1 << tmp_17_fu_575_p2;

assign tmp32_V_5_fu_572_p1 = p_Val2_31_reg_1741[31:0];

assign tmp32_V_6_fu_606_p1 = tmp_91_fu_601_p2[31:0];

assign tmp32_V_7_fu_610_p3 = ((icmp_fu_566_p2[0:0] === 1'b1) ? tmp32_V_3_fu_581_p2 : tmp32_V_6_fu_606_p1);

assign tmp32_V_fu_1543_p1 = grp_fu_336_p1;

assign tmp3_fu_1132_p2 = ($signed(tmp_77_cast_cast_reg_1898) + $signed(tmp_89_cast_cast_fu_1128_p1));

assign tmp_10_fu_967_p2 = (p_shl4_cast_fu_963_p1 + tmp_8_cast_fu_950_p1);

assign tmp_11_fu_451_p3 = {{i_1_reg_1624}, {j_reg_304}};

assign tmp_12_fu_515_p2 = ((p_Val2_23_reg_1717 == 64'd0) ? 1'b1 : 1'b0);

assign tmp_13_fu_510_p2 = (64'd0 - p_Val2_23_reg_1717);


always @ (p_Result_s_fu_525_p4) begin
    if (p_Result_s_fu_525_p4[0] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd0;
    end else if (p_Result_s_fu_525_p4[1] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd1;
    end else if (p_Result_s_fu_525_p4[2] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd2;
    end else if (p_Result_s_fu_525_p4[3] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd3;
    end else if (p_Result_s_fu_525_p4[4] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd4;
    end else if (p_Result_s_fu_525_p4[5] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd5;
    end else if (p_Result_s_fu_525_p4[6] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd6;
    end else if (p_Result_s_fu_525_p4[7] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd7;
    end else if (p_Result_s_fu_525_p4[8] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd8;
    end else if (p_Result_s_fu_525_p4[9] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd9;
    end else if (p_Result_s_fu_525_p4[10] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd10;
    end else if (p_Result_s_fu_525_p4[11] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd11;
    end else if (p_Result_s_fu_525_p4[12] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd12;
    end else if (p_Result_s_fu_525_p4[13] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd13;
    end else if (p_Result_s_fu_525_p4[14] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd14;
    end else if (p_Result_s_fu_525_p4[15] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd15;
    end else if (p_Result_s_fu_525_p4[16] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd16;
    end else if (p_Result_s_fu_525_p4[17] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd17;
    end else if (p_Result_s_fu_525_p4[18] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd18;
    end else if (p_Result_s_fu_525_p4[19] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd19;
    end else if (p_Result_s_fu_525_p4[20] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd20;
    end else if (p_Result_s_fu_525_p4[21] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd21;
    end else if (p_Result_s_fu_525_p4[22] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd22;
    end else if (p_Result_s_fu_525_p4[23] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd23;
    end else if (p_Result_s_fu_525_p4[24] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd24;
    end else if (p_Result_s_fu_525_p4[25] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd25;
    end else if (p_Result_s_fu_525_p4[26] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd26;
    end else if (p_Result_s_fu_525_p4[27] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd27;
    end else if (p_Result_s_fu_525_p4[28] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd28;
    end else if (p_Result_s_fu_525_p4[29] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd29;
    end else if (p_Result_s_fu_525_p4[30] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd30;
    end else if (p_Result_s_fu_525_p4[31] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd31;
    end else if (p_Result_s_fu_525_p4[32] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd32;
    end else if (p_Result_s_fu_525_p4[33] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd33;
    end else if (p_Result_s_fu_525_p4[34] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd34;
    end else if (p_Result_s_fu_525_p4[35] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd35;
    end else if (p_Result_s_fu_525_p4[36] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd36;
    end else if (p_Result_s_fu_525_p4[37] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd37;
    end else if (p_Result_s_fu_525_p4[38] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd38;
    end else if (p_Result_s_fu_525_p4[39] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd39;
    end else if (p_Result_s_fu_525_p4[40] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd40;
    end else if (p_Result_s_fu_525_p4[41] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd41;
    end else if (p_Result_s_fu_525_p4[42] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd42;
    end else if (p_Result_s_fu_525_p4[43] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd43;
    end else if (p_Result_s_fu_525_p4[44] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd44;
    end else if (p_Result_s_fu_525_p4[45] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd45;
    end else if (p_Result_s_fu_525_p4[46] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd46;
    end else if (p_Result_s_fu_525_p4[47] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd47;
    end else if (p_Result_s_fu_525_p4[48] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd48;
    end else if (p_Result_s_fu_525_p4[49] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd49;
    end else if (p_Result_s_fu_525_p4[50] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd50;
    end else if (p_Result_s_fu_525_p4[51] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd51;
    end else if (p_Result_s_fu_525_p4[52] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd52;
    end else if (p_Result_s_fu_525_p4[53] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd53;
    end else if (p_Result_s_fu_525_p4[54] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd54;
    end else if (p_Result_s_fu_525_p4[55] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd55;
    end else if (p_Result_s_fu_525_p4[56] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd56;
    end else if (p_Result_s_fu_525_p4[57] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd57;
    end else if (p_Result_s_fu_525_p4[58] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd58;
    end else if (p_Result_s_fu_525_p4[59] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd59;
    end else if (p_Result_s_fu_525_p4[60] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd60;
    end else if (p_Result_s_fu_525_p4[61] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd61;
    end else if (p_Result_s_fu_525_p4[62] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd62;
    end else if (p_Result_s_fu_525_p4[63] == 1'b1) begin
        tmp_14_fu_535_p3 = 64'd63;
    end else begin
        tmp_14_fu_535_p3 = 64'd64;
    end
end

assign tmp_15_fu_458_p1 = tmp_11_fu_451_p3;

assign tmp_16_fu_976_p4 = {{{i_1_reg_1624}, {j_reg_304}}, {3'd0}};

assign tmp_17_fu_575_p2 = (32'd31 - msb_idx_fu_551_p2);

assign tmp_18_fu_989_p2 = (p_shl3_cast_fu_985_p1 + tmp_37_cast_fu_973_p1);

assign tmp_19_fu_632_p2 = ((p_Result_s_24_fu_622_p4 != 8'd158) ? 1'b1 : 1'b0);

assign tmp_1_fu_1557_p2 = ((p_Result_3_fu_1547_p4 != 8'd158) ? 1'b1 : 1'b0);

assign tmp_20_fu_638_p2 = ($signed(8'd158) - $signed(tmp_50_reg_1752));

assign tmp_21_fu_643_p1 = tmp_19_reg_1767;

assign tmp_22_fu_652_p3 = {{is_neg_reg_1724}, {p_Repl2_4_trunc_fu_646_p2}};

assign tmp_23_fu_463_p3 = {{i_reg_292}, {j_1_reg_1658}};

assign tmp_25_fu_748_p1 = exp_tmp_V_reg_1794;

assign tmp_26_fu_751_p3 = {{1'd1}, {tmp_95_reg_1799}};

assign tmp_27_fu_742_p2 = ((tmp_93_fu_716_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_28_fu_774_p2 = (($signed(F2_fu_768_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign tmp_29_fu_780_p2 = ($signed(12'd4080) + $signed(F2_fu_768_p2));

assign tmp_2_fu_1563_p2 = ($signed(8'd142) - $signed(tmp_reg_2041));

assign tmp_30_fu_786_p2 = (12'd16 - F2_fu_768_p2);

assign tmp_31_fu_800_p2 = ((F2_fu_768_p2 == 12'd16) ? 1'b1 : 1'b0);

assign tmp_32_fu_470_p1 = tmp_23_fu_463_p3;

assign tmp_33_fu_830_p2 = ((sh_amt_reg_1826 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_34_fu_998_p4 = {{{i_reg_292}, {j_1_reg_1658}}, {3'd0}};

assign tmp_35_fu_835_p1 = $unsigned(sh_amt_cast_fu_827_p1);

assign tmp_36_fu_839_p2 = $signed(man_V_2_fu_822_p3) >>> tmp_35_fu_835_p1;

assign tmp_37_cast_fu_973_p1 = tmp_11_reg_1677;

assign tmp_37_fu_1011_p2 = (p_shl2_cast_fu_1007_p1 + tmp_48_cast_fu_995_p1);

assign tmp_38_fu_1041_p2 = tmp_96_fu_1038_p1 << sh_amt_cast_reg_1848;

assign tmp_39_fu_475_p3 = {{i_1_reg_1624}, {j_1_reg_1658}};

assign tmp_3_fu_1577_p3 = {{is_neg_1_reg_1644}, {p_Repl2_1_trunc_fu_1571_p2}};

assign tmp_40_fu_481_p1 = tmp_39_fu_475_p3;

assign tmp_41_fu_1087_p2 = (tmp_55_cast_fu_1083_p1 + tmp_5_reg_1633);

assign tmp_42_fu_1092_p3 = {{tmp_41_fu_1087_p2}, {5'd0}};

assign tmp_43_fu_1100_p3 = {{tmp_41_fu_1087_p2}, {2'd0}};

assign tmp_44_fu_1020_p4 = {{{i_1_reg_1624}, {j_1_reg_1658}}, {3'd0}};

assign tmp_45_fu_1032_p2 = (p_shl1_cast_fu_1028_p1 + tmp_62_cast_fu_1017_p1);

assign tmp_46_fu_670_p4 = {{p_Result_1_fu_659_p5[31:1]}};

assign tmp_48_cast_fu_995_p1 = tmp_23_reg_1692;

assign tmp_48_fu_680_p1 = tmp_46_fu_670_p4;

assign tmp_4_fu_438_p3 = {{i_reg_292}, {j_reg_304}};

assign tmp_50_fu_547_p1 = tmp_14_fu_535_p3[7:0];

assign tmp_52_fu_556_p4 = {{msb_idx_fu_551_p2[31:5]}};

assign tmp_54_fu_1187_p1 = $unsigned(SVM_index_cast_fu_1176_p1);

assign tmp_55_cast_fu_1083_p1 = j_reg_304;

assign tmp_55_fu_1335_p3 = {{p_Val2_7_fu_164}, {16'd0}};

assign tmp_56_fu_1347_p1 = $unsigned(p_Val2_6_cast_fu_1332_p1);

assign tmp_57_fu_690_p1 = p_op_fu_684_p2;

assign tmp_58_fu_1196_p2 = (tmp_72_cast_fu_1192_p1 + 17'd9);

assign tmp_59_fu_1202_p1 = tmp_58_fu_1196_p2;

assign tmp_5_fu_403_p2 = (p_shl_cast_fu_399_p1 - i_cast_fu_375_p1);

assign tmp_60_fu_1370_p3 = {{tmp_85_fu_1360_p4}, {16'd0}};

assign tmp_61_fu_1382_p1 = $unsigned(p_Val2_9_cast_fu_1357_p1);

assign tmp_62_cast_fu_1017_p1 = tmp_39_reg_1702;

assign tmp_62_fu_587_p1 = msb_idx_fu_551_p2[5:0];

assign tmp_63_fu_1245_p2 = (tmp_72_cast_reg_1959 + 17'd18);

assign tmp_64_fu_1250_p1 = tmp_63_fu_1245_p2;

assign tmp_65_fu_1431_p3 = {{tmp_86_reg_2015}, {16'd0}};

assign tmp_66_fu_1442_p1 = $unsigned(p_Val2_10_cast_fu_1428_p1);

assign tmp_67_fu_591_p2 = ($signed(6'd33) + $signed(tmp_62_fu_587_p1));

assign tmp_68_fu_1255_p2 = (tmp_72_cast_reg_1959 + 17'd27);

assign tmp_69_cast_fu_1343_p1 = tmp_55_fu_1335_p3;

assign tmp_69_fu_1260_p1 = tmp_68_fu_1255_p2;

assign tmp_6_fu_953_p4 = {{{i_reg_292}, {j_reg_304}}, {3'd0}};

assign tmp_70_fu_1465_p3 = {{tmp_87_fu_1455_p4}, {16'd0}};

assign tmp_71_fu_1477_p1 = $unsigned(p_Val2_11_cast_fu_1452_p1);

assign tmp_72_cast_fu_1192_p1 = $unsigned(SVM_index_cast_fu_1176_p1);

assign tmp_72_fu_597_p1 = tmp_67_fu_591_p2;

assign tmp_73_fu_1046_p4 = {{tmp_38_fu_1041_p2[31:1]}};

assign tmp_74_fu_1056_p3 = ((isneg_reg_1788[0:0] === 1'b1) ? 31'd2147483647 : 31'd0);

assign tmp_75_fu_1063_p3 = ((sel_tmp5_reg_1853[0:0] === 1'b1) ? tmp_73_fu_1046_p4 : tmp_74_fu_1056_p3);

assign tmp_76_cast_fu_1378_p1 = tmp_60_fu_1370_p3;

assign tmp_76_fu_922_p4 = {{tmp_36_fu_839_p2[31:1]}};

assign tmp_77_cast_cast_fu_1108_p1 = $signed(tmp_43_fu_1100_p3);

assign tmp_77_fu_932_p4 = {{man_V_2_fu_822_p3[31:1]}};

assign tmp_78_fu_942_p3 = ((sel_tmp8_fu_870_p2[0:0] === 1'b1) ? tmp_76_fu_922_p4 : tmp_77_fu_932_p4);

assign tmp_79_fu_1070_p3 = ((or_cond_reg_1858[0:0] === 1'b1) ? tmp_75_fu_1063_p3 : tmp_78_reg_1868);

assign tmp_7_fu_420_p2 = (32'd0 - p_Val2_s_fu_160);

assign tmp_80_fu_1076_p3 = ((or_cond2_reg_1863[0:0] === 1'b1) ? tmp_79_fu_1070_p3 : 31'd0);

assign tmp_81_fu_1146_p2 = (tmp_89_cast_cast_fu_1128_p1 + tmp_10_reg_1873);

assign tmp_82_cast_fu_1438_p1 = tmp_65_fu_1431_p3;

assign tmp_82_fu_1156_p2 = (tmp_89_cast_cast_fu_1128_p1 + tmp_18_reg_1878);

assign tmp_83_fu_1166_p2 = (tmp_89_cast_cast_fu_1128_p1 + tmp_37_reg_1883);

assign tmp_84_cast_fu_1151_p1 = tmp_81_fu_1146_p2;

assign tmp_84_fu_1171_p2 = (tmp_89_cast_cast_fu_1128_p1 + tmp_45_reg_1888);

assign tmp_85_cast_fu_1161_p1 = tmp_82_fu_1156_p2;

assign tmp_85_fu_1360_p4 = {{p_Val2_34_fu_1351_p2[47:16]}};

assign tmp_86_cast_fu_1179_p1 = tmp_83_reg_1934;

assign tmp_87_cast_fu_1183_p1 = tmp_84_reg_1939;

assign tmp_87_fu_1455_p4 = {{p_Val2_36_fu_1446_p2[47:16]}};

assign tmp_88_cast_fu_1473_p1 = tmp_70_fu_1465_p3;

assign tmp_89_cast_cast_fu_1128_p1 = k_reg_316;

assign tmp_8_cast_fu_950_p1 = tmp_4_reg_1667;

assign tmp_8_fu_446_p1 = tmp_4_fu_438_p3;

assign tmp_91_fu_601_p2 = p_Val2_31_reg_1741 >> tmp_72_fu_597_p1;

assign tmp_93_fu_716_p1 = ireg_V_fu_712_p1[62:0];

assign tmp_95_fu_738_p1 = ireg_V_fu_712_p1[51:0];

assign tmp_96_fu_1038_p1 = man_V_2_reg_1843[31:0];

assign tmp_97_fu_806_p4 = {{sh_amt_fu_792_p3[11:5]}};

assign tmp_9_fu_1568_p1 = tmp_1_reg_2051;

assign tmp_fu_1539_p1 = num_zeros_fu_1525_p3[7:0];

assign tmp_s_fu_1505_p2 = ((p_Val2_s_fu_160 == 32'd0) ? 1'b1 : 1'b0);

assign x_fu_705_p3 = ((tmp_12_reg_1735[0:0] === 1'b1) ? 32'd0 : f_3_fu_701_p1);

assign yn_fu_694_p3 = ((tmp_12_reg_1735[0:0] === 1'b1) ? 32'd1597463007 : tmp_57_fu_690_p1);

always @ (posedge ap_clk) begin
    p_Result_2_reg_1810[53:52] <= 2'b01;
    tmp_42_reg_1893[4:0] <= 5'b00000;
    tmp_77_cast_cast_reg_1898[1:0] <= 2'b00;
    tmp_72_cast_reg_1959[16] <= 1'b0;
end

endmodule //svm_detect
