// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="xillybus_wrapper,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.561000,HLS_SYN_LAT=27210,HLS_SYN_TPT=9922,HLS_SYN_MEM=19,HLS_SYN_DSP=35,HLS_SYN_FF=7486,HLS_SYN_LUT=13930}" *)

module xillybus_wrapper (
        ap_clk,
        ap_rst,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write
);


input   ap_clk;
input   ap_rst;
input  [31:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;

wire   [7:0] image_V_i_q0;
wire   [7:0] image_V_i_q1;
wire   [7:0] image_V_t_q0;
wire   [7:0] image_V_t_q1;
wire   [31:0] cells_bin_V_i_q0;
wire   [31:0] cells_bin_V_i_q1;
wire   [31:0] cells_bin_V_t_q0;
wire   [31:0] cells_bin_V_t_q1;
wire   [63:0] cells_mag_sq_V_i_q0;
wire   [63:0] cells_mag_sq_V_i_q1;
wire   [63:0] cells_mag_sq_V_t_q0;
wire   [63:0] cells_mag_sq_V_t_q1;
wire   [31:0] hog_i_q0;
wire   [31:0] hog_t_q0;
wire   [25:0] grad_vote_magnitude_s_i_q0;
wire   [25:0] grad_vote_magnitude_s_t_q0;
wire   [3:0] grad_vote_bin_V_i_q0;
wire   [3:0] grad_vote_bin_V_t_q0;
reg    Loop_1_proc_U0_ap_start;
wire    Loop_1_proc_U0_ap_done;
wire    Loop_1_proc_U0_ap_continue;
wire    Loop_1_proc_U0_ap_idle;
wire    Loop_1_proc_U0_ap_ready;
wire    Loop_1_proc_U0_in_r_read;
wire   [11:0] Loop_1_proc_U0_image_V_address0;
wire    Loop_1_proc_U0_image_V_ce0;
wire    Loop_1_proc_U0_image_V_we0;
wire   [7:0] Loop_1_proc_U0_image_V_d0;
wire   [11:0] Loop_1_proc_U0_image_V_address1;
wire    Loop_1_proc_U0_image_V_ce1;
wire    Loop_1_proc_U0_image_V_we1;
wire   [7:0] Loop_1_proc_U0_image_V_d1;
wire    ap_channel_done_image_V;
wire    Loop_1_proc_U0_image_V_full_n;
wire    compute_gradients_U0_ap_start;
wire    compute_gradients_U0_ap_done;
wire    compute_gradients_U0_ap_continue;
wire    compute_gradients_U0_ap_idle;
wire    compute_gradients_U0_ap_ready;
wire   [11:0] compute_gradients_U0_image_V_address0;
wire    compute_gradients_U0_image_V_ce0;
wire   [11:0] compute_gradients_U0_image_V_address1;
wire    compute_gradients_U0_image_V_ce1;
wire   [11:0] compute_gradients_U0_grad_vote_magnitude_s_address0;
wire    compute_gradients_U0_grad_vote_magnitude_s_ce0;
wire    compute_gradients_U0_grad_vote_magnitude_s_we0;
wire   [25:0] compute_gradients_U0_grad_vote_magnitude_s_d0;
wire   [11:0] compute_gradients_U0_grad_vote_bin_V_address0;
wire    compute_gradients_U0_grad_vote_bin_V_ce0;
wire    compute_gradients_U0_grad_vote_bin_V_we0;
wire   [3:0] compute_gradients_U0_grad_vote_bin_V_d0;
wire    ap_channel_done_grad_vote_bin_V;
wire    compute_gradients_U0_grad_vote_bin_V_full_n;
reg    ap_sync_reg_channel_write_grad_vote_bin_V;
wire    ap_sync_channel_write_grad_vote_bin_V;
wire    ap_channel_done_grad_vote_magnitude_s;
wire    compute_gradients_U0_grad_vote_magnitude_s_full_n;
reg    ap_sync_reg_channel_write_grad_vote_magnitude_s;
wire    ap_sync_channel_write_grad_vote_magnitude_s;
wire    compute_cells_U0_ap_start;
wire    compute_cells_U0_ap_done;
wire    compute_cells_U0_ap_continue;
wire    compute_cells_U0_ap_idle;
wire    compute_cells_U0_ap_ready;
wire   [11:0] compute_cells_U0_grad_vote_magnitude_s_address0;
wire    compute_cells_U0_grad_vote_magnitude_s_ce0;
wire   [11:0] compute_cells_U0_grad_vote_bin_V_address0;
wire    compute_cells_U0_grad_vote_bin_V_ce0;
wire   [9:0] compute_cells_U0_cells_bin_V_address0;
wire    compute_cells_U0_cells_bin_V_ce0;
wire    compute_cells_U0_cells_bin_V_we0;
wire   [31:0] compute_cells_U0_cells_bin_V_d0;
wire   [5:0] compute_cells_U0_cells_mag_sq_V_address0;
wire    compute_cells_U0_cells_mag_sq_V_ce0;
wire    compute_cells_U0_cells_mag_sq_V_we0;
wire   [63:0] compute_cells_U0_cells_mag_sq_V_d0;
wire    ap_channel_done_cells_mag_sq_V;
wire    compute_cells_U0_cells_mag_sq_V_full_n;
reg    ap_sync_reg_channel_write_cells_mag_sq_V;
wire    ap_sync_channel_write_cells_mag_sq_V;
wire    ap_channel_done_cells_bin_V;
wire    compute_cells_U0_cells_bin_V_full_n;
reg    ap_sync_reg_channel_write_cells_bin_V;
wire    ap_sync_channel_write_cells_bin_V;
wire    compute_blocks_U0_ap_start;
wire    compute_blocks_U0_ap_done;
wire    compute_blocks_U0_ap_continue;
wire    compute_blocks_U0_ap_idle;
wire    compute_blocks_U0_ap_ready;
wire   [9:0] compute_blocks_U0_cells_bin_V_address0;
wire    compute_blocks_U0_cells_bin_V_ce0;
wire   [9:0] compute_blocks_U0_cells_bin_V_address1;
wire    compute_blocks_U0_cells_bin_V_ce1;
wire   [5:0] compute_blocks_U0_cells_mag_sq_V_address0;
wire    compute_blocks_U0_cells_mag_sq_V_ce0;
wire   [5:0] compute_blocks_U0_cells_mag_sq_V_address1;
wire    compute_blocks_U0_cells_mag_sq_V_ce1;
wire   [10:0] compute_blocks_U0_hog_address0;
wire    compute_blocks_U0_hog_ce0;
wire    compute_blocks_U0_hog_we0;
wire   [31:0] compute_blocks_U0_hog_d0;
wire   [10:0] compute_blocks_U0_hog_address1;
wire    compute_blocks_U0_hog_ce1;
wire    compute_blocks_U0_hog_we1;
wire   [31:0] compute_blocks_U0_hog_d1;
wire    ap_channel_done_hog;
wire    compute_blocks_U0_hog_full_n;
wire    Loop_2_proc_U0_ap_start;
wire    Loop_2_proc_U0_ap_done;
wire    Loop_2_proc_U0_ap_continue;
wire    Loop_2_proc_U0_ap_idle;
wire    Loop_2_proc_U0_ap_ready;
wire   [31:0] Loop_2_proc_U0_out_r_din;
wire    Loop_2_proc_U0_out_r_write;
wire   [10:0] Loop_2_proc_U0_hog_address0;
wire    Loop_2_proc_U0_hog_ce0;
wire    ap_sync_continue;
wire    image_V_i_full_n;
wire    image_V_t_empty_n;
wire    grad_vote_magnitude_s_i_full_n;
wire    grad_vote_magnitude_s_t_empty_n;
wire    grad_vote_bin_V_i_full_n;
wire    grad_vote_bin_V_t_empty_n;
wire    cells_bin_V_i_full_n;
wire    cells_bin_V_t_empty_n;
wire   [31:0] cells_bin_V_t_d1;
wire    cells_bin_V_t_we1;
wire    cells_mag_sq_V_i_full_n;
wire    cells_mag_sq_V_t_empty_n;
wire   [63:0] cells_mag_sq_V_t_d1;
wire    cells_mag_sq_V_t_we1;
wire    hog_i_full_n;
wire    hog_t_empty_n;
wire    Loop_1_proc_U0_start_full_n;
wire    Loop_1_proc_U0_start_write;
wire    compute_gradients_U0_start_full_n;
wire    compute_gradients_U0_start_write;
wire    compute_cells_U0_start_full_n;
wire    compute_cells_U0_start_write;
wire    compute_blocks_U0_start_full_n;
wire    compute_blocks_U0_start_write;
wire    Loop_2_proc_U0_start_full_n;
wire    Loop_2_proc_U0_start_write;

// power-on initialization
initial begin
#0 Loop_1_proc_U0_ap_start = 1'b0;
#0 ap_sync_reg_channel_write_grad_vote_bin_V = 1'b0;
#0 ap_sync_reg_channel_write_grad_vote_magnitude_s = 1'b0;
#0 ap_sync_reg_channel_write_cells_mag_sq_V = 1'b0;
#0 ap_sync_reg_channel_write_cells_bin_V = 1'b0;
end

xillybus_wrapper_g8j #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
image_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_1_proc_U0_image_V_address0),
    .i_ce0(Loop_1_proc_U0_image_V_ce0),
    .i_we0(Loop_1_proc_U0_image_V_we0),
    .i_d0(Loop_1_proc_U0_image_V_d0),
    .i_q0(image_V_i_q0),
    .i_address1(Loop_1_proc_U0_image_V_address1),
    .i_ce1(Loop_1_proc_U0_image_V_ce1),
    .i_we1(Loop_1_proc_U0_image_V_we1),
    .i_d1(Loop_1_proc_U0_image_V_d1),
    .i_q1(image_V_i_q1),
    .t_address0(compute_gradients_U0_image_V_address0),
    .t_ce0(compute_gradients_U0_image_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(image_V_t_q0),
    .t_address1(compute_gradients_U0_image_V_address1),
    .t_ce1(compute_gradients_U0_image_V_ce1),
    .t_we1(1'b0),
    .t_d1(8'd0),
    .t_q1(image_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(image_V_i_full_n),
    .i_write(Loop_1_proc_U0_ap_done),
    .t_empty_n(image_V_t_empty_n),
    .t_read(compute_gradients_U0_ap_ready)
);

xillybus_wrapper_hbi #(
    .DataWidth( 32 ),
    .AddressRange( 576 ),
    .AddressWidth( 10 ))
cells_bin_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_cells_U0_cells_bin_V_address0),
    .i_ce0(compute_cells_U0_cells_bin_V_ce0),
    .i_we0(compute_cells_U0_cells_bin_V_we0),
    .i_d0(compute_cells_U0_cells_bin_V_d0),
    .i_q0(cells_bin_V_i_q0),
    .i_address1(10'd0),
    .i_ce1(1'b0),
    .i_q1(cells_bin_V_i_q1),
    .t_address0(compute_blocks_U0_cells_bin_V_address0),
    .t_ce0(compute_blocks_U0_cells_bin_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(cells_bin_V_t_q0),
    .t_address1(compute_blocks_U0_cells_bin_V_address1),
    .t_ce1(compute_blocks_U0_cells_bin_V_ce1),
    .t_q1(cells_bin_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(cells_bin_V_i_full_n),
    .i_write(ap_channel_done_cells_bin_V),
    .t_empty_n(cells_bin_V_t_empty_n),
    .t_read(compute_blocks_U0_ap_ready)
);

xillybus_wrapper_ibs #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
cells_mag_sq_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_cells_U0_cells_mag_sq_V_address0),
    .i_ce0(compute_cells_U0_cells_mag_sq_V_ce0),
    .i_we0(compute_cells_U0_cells_mag_sq_V_we0),
    .i_d0(compute_cells_U0_cells_mag_sq_V_d0),
    .i_q0(cells_mag_sq_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(cells_mag_sq_V_i_q1),
    .t_address0(compute_blocks_U0_cells_mag_sq_V_address0),
    .t_ce0(compute_blocks_U0_cells_mag_sq_V_ce0),
    .t_we0(1'b0),
    .t_d0(64'd0),
    .t_q0(cells_mag_sq_V_t_q0),
    .t_address1(compute_blocks_U0_cells_mag_sq_V_address1),
    .t_ce1(compute_blocks_U0_cells_mag_sq_V_ce1),
    .t_q1(cells_mag_sq_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(cells_mag_sq_V_i_full_n),
    .i_write(ap_channel_done_cells_mag_sq_V),
    .t_empty_n(cells_mag_sq_V_t_empty_n),
    .t_read(compute_blocks_U0_ap_ready)
);

xillybus_wrapper_jbC #(
    .DataWidth( 32 ),
    .AddressRange( 1764 ),
    .AddressWidth( 11 ))
hog_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_blocks_U0_hog_address0),
    .i_ce0(compute_blocks_U0_hog_ce0),
    .i_we0(compute_blocks_U0_hog_we0),
    .i_d0(compute_blocks_U0_hog_d0),
    .i_q0(hog_i_q0),
    .i_address1(compute_blocks_U0_hog_address1),
    .i_ce1(compute_blocks_U0_hog_ce1),
    .i_we1(compute_blocks_U0_hog_we1),
    .i_d1(compute_blocks_U0_hog_d1),
    .t_address0(Loop_2_proc_U0_hog_address0),
    .t_ce0(Loop_2_proc_U0_hog_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(hog_t_q0),
    .t_address1(11'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(32'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(hog_i_full_n),
    .i_write(compute_blocks_U0_ap_done),
    .t_empty_n(hog_t_empty_n),
    .t_read(Loop_2_proc_U0_ap_ready)
);

xillybus_wrapper_kbM #(
    .DataWidth( 26 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
grad_vote_magnitude_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_gradients_U0_grad_vote_magnitude_s_address0),
    .i_ce0(compute_gradients_U0_grad_vote_magnitude_s_ce0),
    .i_we0(compute_gradients_U0_grad_vote_magnitude_s_we0),
    .i_d0(compute_gradients_U0_grad_vote_magnitude_s_d0),
    .i_q0(grad_vote_magnitude_s_i_q0),
    .t_address0(compute_cells_U0_grad_vote_magnitude_s_address0),
    .t_ce0(compute_cells_U0_grad_vote_magnitude_s_ce0),
    .t_we0(1'b0),
    .t_d0(26'd0),
    .t_q0(grad_vote_magnitude_s_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(grad_vote_magnitude_s_i_full_n),
    .i_write(ap_channel_done_grad_vote_magnitude_s),
    .t_empty_n(grad_vote_magnitude_s_t_empty_n),
    .t_read(compute_cells_U0_ap_ready)
);

xillybus_wrapper_lbW #(
    .DataWidth( 4 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
grad_vote_bin_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_gradients_U0_grad_vote_bin_V_address0),
    .i_ce0(compute_gradients_U0_grad_vote_bin_V_ce0),
    .i_we0(compute_gradients_U0_grad_vote_bin_V_we0),
    .i_d0(compute_gradients_U0_grad_vote_bin_V_d0),
    .i_q0(grad_vote_bin_V_i_q0),
    .t_address0(compute_cells_U0_grad_vote_bin_V_address0),
    .t_ce0(compute_cells_U0_grad_vote_bin_V_ce0),
    .t_we0(1'b0),
    .t_d0(4'd0),
    .t_q0(grad_vote_bin_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(grad_vote_bin_V_i_full_n),
    .i_write(ap_channel_done_grad_vote_bin_V),
    .t_empty_n(grad_vote_bin_V_t_empty_n),
    .t_read(compute_cells_U0_ap_ready)
);

Loop_1_proc Loop_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_1_proc_U0_ap_start),
    .ap_done(Loop_1_proc_U0_ap_done),
    .ap_continue(Loop_1_proc_U0_ap_continue),
    .ap_idle(Loop_1_proc_U0_ap_idle),
    .ap_ready(Loop_1_proc_U0_ap_ready),
    .in_r_dout(in_r_dout),
    .in_r_empty_n(in_r_empty_n),
    .in_r_read(Loop_1_proc_U0_in_r_read),
    .image_V_address0(Loop_1_proc_U0_image_V_address0),
    .image_V_ce0(Loop_1_proc_U0_image_V_ce0),
    .image_V_we0(Loop_1_proc_U0_image_V_we0),
    .image_V_d0(Loop_1_proc_U0_image_V_d0),
    .image_V_address1(Loop_1_proc_U0_image_V_address1),
    .image_V_ce1(Loop_1_proc_U0_image_V_ce1),
    .image_V_we1(Loop_1_proc_U0_image_V_we1),
    .image_V_d1(Loop_1_proc_U0_image_V_d1)
);

compute_gradients compute_gradients_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_gradients_U0_ap_start),
    .ap_done(compute_gradients_U0_ap_done),
    .ap_continue(compute_gradients_U0_ap_continue),
    .ap_idle(compute_gradients_U0_ap_idle),
    .ap_ready(compute_gradients_U0_ap_ready),
    .image_V_address0(compute_gradients_U0_image_V_address0),
    .image_V_ce0(compute_gradients_U0_image_V_ce0),
    .image_V_q0(image_V_t_q0),
    .image_V_address1(compute_gradients_U0_image_V_address1),
    .image_V_ce1(compute_gradients_U0_image_V_ce1),
    .image_V_q1(image_V_t_q1),
    .grad_vote_magnitude_s_address0(compute_gradients_U0_grad_vote_magnitude_s_address0),
    .grad_vote_magnitude_s_ce0(compute_gradients_U0_grad_vote_magnitude_s_ce0),
    .grad_vote_magnitude_s_we0(compute_gradients_U0_grad_vote_magnitude_s_we0),
    .grad_vote_magnitude_s_d0(compute_gradients_U0_grad_vote_magnitude_s_d0),
    .grad_vote_bin_V_address0(compute_gradients_U0_grad_vote_bin_V_address0),
    .grad_vote_bin_V_ce0(compute_gradients_U0_grad_vote_bin_V_ce0),
    .grad_vote_bin_V_we0(compute_gradients_U0_grad_vote_bin_V_we0),
    .grad_vote_bin_V_d0(compute_gradients_U0_grad_vote_bin_V_d0)
);

compute_cells compute_cells_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_cells_U0_ap_start),
    .ap_done(compute_cells_U0_ap_done),
    .ap_continue(compute_cells_U0_ap_continue),
    .ap_idle(compute_cells_U0_ap_idle),
    .ap_ready(compute_cells_U0_ap_ready),
    .grad_vote_magnitude_s_address0(compute_cells_U0_grad_vote_magnitude_s_address0),
    .grad_vote_magnitude_s_ce0(compute_cells_U0_grad_vote_magnitude_s_ce0),
    .grad_vote_magnitude_s_q0(grad_vote_magnitude_s_t_q0),
    .grad_vote_bin_V_address0(compute_cells_U0_grad_vote_bin_V_address0),
    .grad_vote_bin_V_ce0(compute_cells_U0_grad_vote_bin_V_ce0),
    .grad_vote_bin_V_q0(grad_vote_bin_V_t_q0),
    .cells_bin_V_address0(compute_cells_U0_cells_bin_V_address0),
    .cells_bin_V_ce0(compute_cells_U0_cells_bin_V_ce0),
    .cells_bin_V_we0(compute_cells_U0_cells_bin_V_we0),
    .cells_bin_V_d0(compute_cells_U0_cells_bin_V_d0),
    .cells_mag_sq_V_address0(compute_cells_U0_cells_mag_sq_V_address0),
    .cells_mag_sq_V_ce0(compute_cells_U0_cells_mag_sq_V_ce0),
    .cells_mag_sq_V_we0(compute_cells_U0_cells_mag_sq_V_we0),
    .cells_mag_sq_V_d0(compute_cells_U0_cells_mag_sq_V_d0)
);

compute_blocks compute_blocks_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_blocks_U0_ap_start),
    .ap_done(compute_blocks_U0_ap_done),
    .ap_continue(compute_blocks_U0_ap_continue),
    .ap_idle(compute_blocks_U0_ap_idle),
    .ap_ready(compute_blocks_U0_ap_ready),
    .cells_bin_V_address0(compute_blocks_U0_cells_bin_V_address0),
    .cells_bin_V_ce0(compute_blocks_U0_cells_bin_V_ce0),
    .cells_bin_V_q0(cells_bin_V_t_q0),
    .cells_bin_V_address1(compute_blocks_U0_cells_bin_V_address1),
    .cells_bin_V_ce1(compute_blocks_U0_cells_bin_V_ce1),
    .cells_bin_V_q1(cells_bin_V_t_q1),
    .cells_mag_sq_V_address0(compute_blocks_U0_cells_mag_sq_V_address0),
    .cells_mag_sq_V_ce0(compute_blocks_U0_cells_mag_sq_V_ce0),
    .cells_mag_sq_V_q0(cells_mag_sq_V_t_q0),
    .cells_mag_sq_V_address1(compute_blocks_U0_cells_mag_sq_V_address1),
    .cells_mag_sq_V_ce1(compute_blocks_U0_cells_mag_sq_V_ce1),
    .cells_mag_sq_V_q1(cells_mag_sq_V_t_q1),
    .hog_address0(compute_blocks_U0_hog_address0),
    .hog_ce0(compute_blocks_U0_hog_ce0),
    .hog_we0(compute_blocks_U0_hog_we0),
    .hog_d0(compute_blocks_U0_hog_d0),
    .hog_address1(compute_blocks_U0_hog_address1),
    .hog_ce1(compute_blocks_U0_hog_ce1),
    .hog_we1(compute_blocks_U0_hog_we1),
    .hog_d1(compute_blocks_U0_hog_d1)
);

Loop_2_proc Loop_2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_2_proc_U0_ap_start),
    .ap_done(Loop_2_proc_U0_ap_done),
    .ap_continue(Loop_2_proc_U0_ap_continue),
    .ap_idle(Loop_2_proc_U0_ap_idle),
    .ap_ready(Loop_2_proc_U0_ap_ready),
    .out_r_din(Loop_2_proc_U0_out_r_din),
    .out_r_full_n(out_r_full_n),
    .out_r_write(Loop_2_proc_U0_out_r_write),
    .hog_address0(Loop_2_proc_U0_hog_address0),
    .hog_ce0(Loop_2_proc_U0_hog_ce0),
    .hog_q0(hog_t_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Loop_1_proc_U0_ap_start <= 1'b0;
    end else begin
        Loop_1_proc_U0_ap_start <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_cells_bin_V <= 1'b0;
    end else begin
        if (((compute_cells_U0_ap_done & compute_cells_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_cells_bin_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_cells_bin_V <= ap_sync_channel_write_cells_bin_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_cells_mag_sq_V <= 1'b0;
    end else begin
        if (((compute_cells_U0_ap_done & compute_cells_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_cells_mag_sq_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_cells_mag_sq_V <= ap_sync_channel_write_cells_mag_sq_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_grad_vote_bin_V <= 1'b0;
    end else begin
        if (((compute_gradients_U0_ap_done & compute_gradients_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_grad_vote_bin_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_grad_vote_bin_V <= ap_sync_channel_write_grad_vote_bin_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_grad_vote_magnitude_s <= 1'b0;
    end else begin
        if (((compute_gradients_U0_ap_done & compute_gradients_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_grad_vote_magnitude_s <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_grad_vote_magnitude_s <= ap_sync_channel_write_grad_vote_magnitude_s;
        end
    end
end

assign Loop_1_proc_U0_ap_continue = image_V_i_full_n;

assign Loop_1_proc_U0_image_V_full_n = image_V_i_full_n;

assign Loop_1_proc_U0_start_full_n = 1'b1;

assign Loop_1_proc_U0_start_write = 1'b0;

assign Loop_2_proc_U0_ap_continue = 1'b1;

assign Loop_2_proc_U0_ap_start = hog_t_empty_n;

assign Loop_2_proc_U0_start_full_n = 1'b1;

assign Loop_2_proc_U0_start_write = 1'b0;

assign ap_channel_done_cells_bin_V = ((ap_sync_reg_channel_write_cells_bin_V ^ 1'b1) & compute_cells_U0_ap_done);

assign ap_channel_done_cells_mag_sq_V = ((ap_sync_reg_channel_write_cells_mag_sq_V ^ 1'b1) & compute_cells_U0_ap_done);

assign ap_channel_done_grad_vote_bin_V = ((ap_sync_reg_channel_write_grad_vote_bin_V ^ 1'b1) & compute_gradients_U0_ap_done);

assign ap_channel_done_grad_vote_magnitude_s = ((ap_sync_reg_channel_write_grad_vote_magnitude_s ^ 1'b1) & compute_gradients_U0_ap_done);

assign ap_channel_done_hog = compute_blocks_U0_ap_done;

assign ap_channel_done_image_V = Loop_1_proc_U0_ap_done;

assign ap_sync_channel_write_cells_bin_V = ((compute_cells_U0_cells_bin_V_full_n & ap_channel_done_cells_bin_V) | ap_sync_reg_channel_write_cells_bin_V);

assign ap_sync_channel_write_cells_mag_sq_V = ((compute_cells_U0_cells_mag_sq_V_full_n & ap_channel_done_cells_mag_sq_V) | ap_sync_reg_channel_write_cells_mag_sq_V);

assign ap_sync_channel_write_grad_vote_bin_V = ((compute_gradients_U0_grad_vote_bin_V_full_n & ap_channel_done_grad_vote_bin_V) | ap_sync_reg_channel_write_grad_vote_bin_V);

assign ap_sync_channel_write_grad_vote_magnitude_s = ((compute_gradients_U0_grad_vote_magnitude_s_full_n & ap_channel_done_grad_vote_magnitude_s) | ap_sync_reg_channel_write_grad_vote_magnitude_s);

assign ap_sync_continue = 1'b0;

assign cells_bin_V_t_d1 = 32'd0;

assign cells_bin_V_t_we1 = 1'b0;

assign cells_mag_sq_V_t_d1 = 64'd0;

assign cells_mag_sq_V_t_we1 = 1'b0;

assign compute_blocks_U0_ap_continue = hog_i_full_n;

assign compute_blocks_U0_ap_start = (cells_mag_sq_V_t_empty_n & cells_bin_V_t_empty_n);

assign compute_blocks_U0_hog_full_n = hog_i_full_n;

assign compute_blocks_U0_start_full_n = 1'b1;

assign compute_blocks_U0_start_write = 1'b0;

assign compute_cells_U0_ap_continue = (ap_sync_channel_write_cells_mag_sq_V & ap_sync_channel_write_cells_bin_V);

assign compute_cells_U0_ap_start = (grad_vote_magnitude_s_t_empty_n & grad_vote_bin_V_t_empty_n);

assign compute_cells_U0_cells_bin_V_full_n = cells_bin_V_i_full_n;

assign compute_cells_U0_cells_mag_sq_V_full_n = cells_mag_sq_V_i_full_n;

assign compute_cells_U0_start_full_n = 1'b1;

assign compute_cells_U0_start_write = 1'b0;

assign compute_gradients_U0_ap_continue = (ap_sync_channel_write_grad_vote_magnitude_s & ap_sync_channel_write_grad_vote_bin_V);

assign compute_gradients_U0_ap_start = image_V_t_empty_n;

assign compute_gradients_U0_grad_vote_bin_V_full_n = grad_vote_bin_V_i_full_n;

assign compute_gradients_U0_grad_vote_magnitude_s_full_n = grad_vote_magnitude_s_i_full_n;

assign compute_gradients_U0_start_full_n = 1'b1;

assign compute_gradients_U0_start_write = 1'b0;

assign in_r_read = Loop_1_proc_U0_in_r_read;

assign out_r_din = Loop_2_proc_U0_out_r_din;

assign out_r_write = Loop_2_proc_U0_out_r_write;

endmodule //xillybus_wrapper
