# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo.xci
# IP: The module: 'vga_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo.xci
# IP: The module: 'vga_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/lolic/Documents/Thesis/Zybo_FPGA_bitstream/vivado-essentials/vga_fifo/vga_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
